/* Offline UI fixture. All records are fictional. No HTTP or AI is performed. */
(function(){
  const C=window.AIZCore, index=new C.LocalIndex(), subscribers=new Set();
  const sample=[
    ['Generative models for biomedical image understanding','Diffusion-based cell segmentation, topology-aware decoding and zero-shot generalization.','bio-vision','生成模型将分割输出表达为可编辑图像；本条为界面演示数据，不代表真实论文结论。',['diffusion','segmentation']],
    ['Scientific agents for spatial transcriptomics data curation','Spatial omics datasets, automated metadata extraction and reusable analysis workflows.','spatial','从公开空间组学数据构建可分析资料，关注元数据一致性和可复现性。',['spatial transcriptomics','scientific agent']],
    ['Selection and judging in multi-agent reasoning systems','LLM judge candidate selection, multi agent reasoning and evaluation.','agents','比较候选生成与答案选择两个环节，分析评判信号的适用边界。',['multiagent','llm judge']],
    ['Vision-language-action policies for robotic ultrasound','Medical robotics and ultrasound simulation with vision language action models.','robotics','将视觉理解与探头控制联系起来，关注仿真到真实环境的差异。',['medical robotics','ultrasound']],
    ['Reliable few-shot cell segmentation across imaging modalities','Biomedical segmentation with generative foundation models and calibrated uncertainty.','bio-vision','跨成像模态的少样本分割；演示任务、方法和不确定性标签。',['cell segmentation','foundation model']],
    ['Benchmarking clinical agents with longitudinal trajectories','Agentic clinical diagnosis, reinforcement learning and reproducible evaluation.','agents','采用纵向病例轨迹组织智能体评估，注意信息泄漏与基线可比性。',['agentic','reinforcement learning']]
  ];
  sample.forEach(([title,abstract,topic,summary,tags],i)=>index.upsert({schema:1,id:String(i+1),key:'DEMO000'+i,libraryID:1,itemType:'journalArticle',title,abstract,doi:'10.0000/demo-'+i,year:'2026',author:'Demo Researcher',authors:['Demo Researcher'],date:'2026-09-14',journal:'FICTIONAL · UI demonstration',url:'https://example.org',text:'This is fictional demonstration text, not a real paper. '+abstract,textCoverage:'演示文本（不是真实全文）',tags:['Demo'],topicIDs:[topic],attachments:[{id:100+i,key:'DEMOFILE'+i,filename:'paper-'+i+'.pdf',path:'/demo/paper-'+i+'.pdf',exists:true,stored:true,linked:false}],ai:{summary,problem:'跨数据集泛化',method:'示范方法描述',limitations:'这不是实际文献，只用于检查界面。',tasks:['segmentation'],datasets:[],tags,aliases:['细胞分割','生成模型'],topicIDs:[topic]}}));
  const papers=[{id:'radar-1',source:'arxiv',title:'Generative foundation models for cell segmentation: an illustrative new paper',abstract:'Biomedical segmentation diffusion foundation model with histopathology evaluation.',published:'2026-09-14',url:'https://example.org',authors:['Demo Author'],firstSeen:'2026-09-14T00:00:00Z'},{id:'radar-2',source:'epmc',title:'Spatial omics discovery with scientific agents: interface example',abstract:'Spatial transcriptomics data curation with scientific agent systems.',published:'2026-09-14',url:'https://example.org',authors:['Demo Author'],firstSeen:'2026-09-14T00:00:00Z'}];
  const studio={demo:true,ready:true,paused:false,index,warnings:[],status:'离线界面演示 · 所有数据均为虚构',config:JSON.parse(JSON.stringify(C.DEFAULTS)),state:{usage:{calls:0,tokens:0},seeds:['1','3'],failed:{},journal:[],deferred:[],radar:{papers,sources:{arxiv:{lastFetched:'2026-09-14T10:00:00Z',fetched:1,total:1,range:{since:'2026-09-01',until:'2026-09-14'}},epmc:{lastFetched:'2026-09-14T10:00:00Z',fetched:1,total:1,range:{since:'2026-09-01',until:'2026-09-14'}}}}},
    get docs(){return [...index.docs.values()];},selectedIDs:()=>[],subscribe(fn){subscribers.add(fn);return()=>subscribers.delete(fn);},emit(){subscribers.forEach(fn=>fn());},startWorker(){},safeError:e=>e.message,configSnapshot(){return structuredClone(this.config);},hasKey:()=>false,
    async saveSettings(c){this.config=C.validateConfig(c);this.emit();},setKey:async()=>{},testConnection:async()=>'DEMO ONLY — no actual connection',async search(q){return index.search(q);},enqueue(){this.status='演示模式：未发起 API 请求';this.emit();},scanLibrary:async()=>({items:6,queued:0}),
    openItem:async(id)=>{studio.status='演示模式：定位文献 '+id;studio.emit();},openURL:()=>{},async setSeed(id,en){this.state.seeds=en?[...new Set([...this.state.seeds,String(id)])]:this.state.seeds.filter(x=>x!==String(id));this.emit();},
    getDuplicates:()=>[],organizationPlan(ids){return ids.map(id=>({id,title:index.docs.get(id)?.title,topics:['演示分组'],topicIDs:['bio-vision'],tags:['AI/demo'],source:'演示建议'}));},organize:async()=>0,filePlan:async()=>[],renameFiles:async()=>({count:0,failures:[]}),undoLast:async()=>{},convertLinked:async()=>{},mergeExact:async()=>{},
    radar(){return C.rankRadar(papers,this.config.profiles,index,this.state.seeds,Date.parse('2026-09-14'));},refreshRadar:async()=>studio.radar(),explainRadar:async()=>[],importPaper:async()=>({id:'1',existed:true}),exportText:async()=>true,
    assistant:async()=>({answer:'这是离线界面演示，不会调用模型。实际插件会检索选中文献和本地索引后发送必要材料，并提供 [P1] 形式的引用。',references:[{ref:'P1',id:'1',title:sample[0][0]}]})};
  window.__AI_ZOTERO_DEMO__={studio,core:C};
})();
